# Generated by Django 4.0 on 2024-05-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picture_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
